name: checkmarx_scan
run-name: 'build - ${{ github.event.head_commit.message }}'
'on':
  push:
    branches:
      - main
      - master
jobs:
  build-service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      ENV_KEY: dev
    steps:
      - uses: actions/checkout@v4
      - id: read_config
        name: Read Configuration File
        run: |
          echo "checkmarx_scan"
